### ISSUE TITLE
how to generate dll file on windows10?

### ISSUE THREAD

**Issue by shining-love** [Wulingtian/yolov5_tensorrt_int8#8]
hello, how to generate dll file on windows10?I try it but i met some error in common.h

**Comment by shining-love** [comment]
I have solved the problem, successfully generated the DLL, and completed the call to the DLL.

**Comment by Puzhihui** [comment]
你好，可以分享一下吗

**Comment by Puzhihui** [comment]
> I have solved the problem, successfully generated the DLL, and completed the call to the DLL.
你好，可以分享一下吗

**Comment by Puzhihui** [comment]
@yang-gis
